FROM golang:1.10.1
LABEL Maintainer mlabouardy

ENV VERSION v0.0.23

COPY Gopkg.lock .

RUN wget https://github.com/sonatype-nexus-community/nancy/releases/download/$VERSION/nancy-linux.amd64-$VERSION -O nancy && \
    chmod +x nancy

CMD ./nancy Gopkg.lock